### ISSUE TITLE
PSR-12 - line length should be soft limit

### ISSUE THREAD

**Issue by rasmus0201** [Tarik02/js-php-imports#1]
Hi. Awesome package you got here!

Currently when having PSR-12 enabled a formatting of:
```php
use App\Dictionary\DictionaryInterface;
use App\Dictionary\Vendor\Article\DanishArabic\Model\ArabicDanishArticle;
use App\Dictionary\Vendor\Article\DanishArabic\Model\ArabicDanishArticleRepository;
use App\Dictionary\Vendor\Article\DanishArabic\Model\DanishArabicArticleRepository;
use App\Dictionary\SearchableInterface;
use App\Search\FuzzyResultInterface;
use App\Search\Search;
use App\Search\SearchResult;
use Twig\Environment as Twig;
```

becomes:
```php
use App\Dictionary\Vendor\Article\DanishArabic\Model\{
    ArabicDanishArticle,
    ArabicDanishArticleRepository,
    DanishArabicArticleRepository
};
use App\Dictionary\{
    DictionaryInterface,
    SearchableInterface
};
use App\Search\{
    FuzzyResultInterface,
    Search,
    SearchResult
};
use Twig\Environment as Twig;
```

with the following config:
```json
{
    "php-imports.sort.order": "default",
    "php-imports.sort.nestedOrder": "default",
    "php-imports.psr12.enable": true,
    "php-imports.psr12.isolateModifiers": false,
    "php-imports.unused.enable": true,
    "php-imports.psr12.minGroupUsesCount": 2,
    "php-imports.psr12.minNestedGroupUsesCount": 2,
    "php-imports.psr12.minNestedGroupNestedUsesCount": 2,
}
```

I would not expect the groups to be nested in multiple lines and it actually makes the imports "blocks" span more lines than before the format. I tested with and without the PSR-12 settings, and it seems to be the one triggering the grouping. I could suspect it has something to do with the line-length perhaps?

I would like the result to be:
```php
use App\Dictionary\Vendor\Article\DanishArabic\Model\{ArabicDanishArticle, ArabicDanishArticleRepository, DanishArabicArticleRepository};
use App\Dictionary\{DictionaryInterface, SearchableInterface};
use App\Search\{FuzzyResultInterface, Search, SearchResult};
use Twig\Environment as Twig;
```

So perhaps a new setting to toggle grouping newlines? Maybe also a setting to enforce a max line-length? 

Thank you!

**Comment by Tarik02** [comment]
Hello!
I think this is good idea, but I would like to implement it as optional feature so it won't break compatibility with old configs.

Actually, now it always puts every use statement in a separate line no matter how long or short it is. So, there's need to implement two news settings: one to control whether to put multiple grouped imports in a single line, and another one to control this limit.

**Comment by rasmus0201** [comment]
Thank you for this, it is perfect! 🙌
